/**
 * Style Dictionary v4 configuration
 *
 * Pipeline:
 *   tokens/01-primitive.json  ─┐
 *   tokens/02-semantic.json    ├─► CSS custom props  → src/styles/generated/tokens.css
 *   tokens/03-dark.json        ├─► Dark-mode props   → src/styles/generated/dark.css
 *   tokens/04-motion.json      ├─► JS/TS tokens      → src/lib/generated/tokens.ts
 *                              └─► Tailwind extension→ src/styles/generated/tailwind-tokens.cjs
 */

import StyleDictionary from "style-dictionary";
import { register, getTransforms } from "@tokens-studio/sd-transforms";
import { promises as fs } from "fs";

// ─── Register Tokens Studio preprocessor + transforms ────────────────────────
register(StyleDictionary);

// ─── Ensure output dirs exist ─────────────────────────────────────────────────
await fs.mkdir("src/styles/generated", { recursive: true });
await fs.mkdir("src/lib/generated", { recursive: true });

// ─── Custom transform: cubicBezier array → CSS cubic-bezier() string ──────────
StyleDictionary.registerTransform({
  name: "duck/cubicBezier/css",
  type: "value",
  transitive: true,
  filter: (token) => {
    const type = token.$type ?? token.type;
    return type === "cubicBezier";
  },
  transform: (token) => {
    const v = token.$value ?? token.value;
    if (Array.isArray(v)) return `cubic-bezier(${v.join(", ")})`;
    return v;
  },
});

// ─── Register custom transform groups ────────────────────────────────────────
// duck/css — for CSS variable output (kebab-case names)
StyleDictionary.registerTransformGroup({
  name: "duck/css",
  transforms: [
    ...getTransforms(),          // all ts/* transforms from Tokens Studio
    "duck/cubicBezier/css",      // cubicBezier → cubic-bezier() string
    "name/kebab",                // token.path → kebab-case (e.g. color-bg-page)
  ],
});

// duck/js — for JS/TS token object output (camelCase names)
StyleDictionary.registerTransformGroup({
  name: "duck/js",
  transforms: [
    ...getTransforms(),
    "duck/cubicBezier/css",
    "name/camel",
  ],
});

// ─── Custom format: Tailwind CSS extension ────────────────────────────────────
StyleDictionary.registerFormat({
  name: "duck/tailwind-tokens",
  format: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const borderRadius = {};
    const duration = {};
    const easing = {};

    for (const token of dictionary.allTokens) {
      const name = token.name; // kebab-case, e.g. "color-bg-page"
      const cssVar = `var(--${name})`;
      const type = token.$type ?? token.type;

      if (type === "color") {
        colors[name] = cssVar;
      } else if (type === "dimension" && name.startsWith("space-")) {
        spacing[name] = cssVar;
      } else if (type === "dimension" && name.startsWith("radius-")) {
        borderRadius[name] = cssVar;
      } else if (type === "duration") {
        duration[name] = cssVar;
      } else if (type === "cubicBezier") {
        easing[name] = cssVar;
      }
    }

    return [
      "/** Auto-generated by Style Dictionary — do not edit manually. */",
      "/** Source: tokens/02-semantic.json + tokens/04-motion.json      */",
      "// eslint-disable-next-line @typescript-eslint/no-require-imports",
      "module.exports = {",
      `  colors: ${JSON.stringify(colors, null, 4)},`,
      `  spacing: ${JSON.stringify(spacing, null, 4)},`,
      `  borderRadius: ${JSON.stringify(borderRadius, null, 4)},`,
      `  transitionDuration: ${JSON.stringify(duration, null, 4)},`,
      `  transitionTimingFunction: ${JSON.stringify(easing, null, 4)},`,
      "};",
    ].join("\n");
  },
});

// ─── Custom format: TypeScript token object ───────────────────────────────────
StyleDictionary.registerFormat({
  name: "duck/typescript-tokens",
  format: ({ dictionary }) => {
    const buildNested = (tokens) => {
      const result = {};
      for (const token of tokens) {
        let cursor = result;
        for (let i = 0; i < token.path.length - 1; i++) {
          const key = token.path[i];
          cursor[key] = cursor[key] ?? {};
          cursor = cursor[key];
        }
        const leaf = token.path[token.path.length - 1];
        const type = token.$type ?? token.type;
        const val = token.value ?? token.$value;

        if (type === "cubicBezier") {
          // Store as number[] for Framer Motion
          cursor[leaf] = Array.isArray(token.$value) ? token.$value : val;
        } else if (type === "duration") {
          // Keep as string with units (e.g. "200ms")
          cursor[leaf] = val;
        } else {
          cursor[leaf] = val;
        }
      }
      return result;
    };

    const nested = buildNested(dictionary.allTokens);

    return [
      "/** Auto-generated by Style Dictionary — do not edit manually. */",
      "/** Import for type-safe token access and Motion animation values. */",
      "",
      `export const tokens = ${JSON.stringify(nested, null, 2)} as const;`,
      "",
      "export type Tokens = typeof tokens;",
    ].join("\n");
  },
});

// ─── Primitive groups output directly (space, radius, font) ──────────────────
const PRIMITIVE_PASS_THROUGH = ["space", "radius", "font"];

// ═══════════════════════════════════════════════════════════════════════════════
// BUILD 1 — Light-mode CSS variables (:root)
//   source = all files (so primitives are available for reference AND output)
//   filter = only output: semantic colors, motion, and primitive space/radius/font
// ═══════════════════════════════════════════════════════════════════════════════
const sdLight = new StyleDictionary({
  source: [
    "tokens/01-primitive.json",
    "tokens/02-semantic.json",
    "tokens/04-motion.json",
  ],
  preprocessors: ["tokens-studio"],
  platforms: {
    css: {
      transformGroup: "duck/css",
      buildPath: "src/styles/generated/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          // Output: semantic tokens + primitive space/radius/font + motion
          // Exclude: raw primitive colors (neutral.50, blue.600, etc.)
          filter: (token) => {
            const fp = token.filePath ?? "";
            if (fp.includes("02-semantic") || fp.includes("04-motion")) return true;
            if (fp.includes("01-primitive")) {
              return PRIMITIVE_PASS_THROUGH.includes(token.path[0]);
            }
            return false;
          },
          options: {
            selector: ":root",
            outputReferences: false,
          },
        },
      ],
    },
  },
});

// ═══════════════════════════════════════════════════════════════════════════════
// BUILD 2 — Dark-mode CSS variables (.dark selector)
// ═══════════════════════════════════════════════════════════════════════════════
const sdDark = new StyleDictionary({
  source: ["tokens/01-primitive.json", "tokens/03-dark.json"],
  preprocessors: ["tokens-studio"],
  platforms: {
    css: {
      transformGroup: "duck/css",
      buildPath: "src/styles/generated/",
      files: [
        {
          destination: "dark.css",
          format: "css/variables",
          filter: (token) => (token.filePath ?? "").includes("03-dark"),
          options: {
            selector: ".dark",
            outputReferences: false,
          },
        },
      ],
    },
  },
});

// ═══════════════════════════════════════════════════════════════════════════════
// BUILD 3 — TypeScript token object (for Motion / JS usage)
// ═══════════════════════════════════════════════════════════════════════════════
const sdTS = new StyleDictionary({
  source: ["tokens/01-primitive.json", "tokens/02-semantic.json", "tokens/04-motion.json"],
  preprocessors: ["tokens-studio"],
  platforms: {
    ts: {
      transformGroup: "duck/js",
      buildPath: "src/lib/generated/",
      files: [
        {
          destination: "tokens.ts",
          format: "duck/typescript-tokens",
          filter: (token) => {
            const fp = token.filePath ?? "";
            if (fp.includes("02-semantic") || fp.includes("04-motion")) return true;
            if (fp.includes("01-primitive")) return PRIMITIVE_PASS_THROUGH.includes(token.path[0]);
            return false;
          },
        },
      ],
    },
  },
});

// ═══════════════════════════════════════════════════════════════════════════════
// BUILD 4 — Tailwind CSS extension (semantic tokens → CSS var references)
// ═══════════════════════════════════════════════════════════════════════════════
const sdTailwind = new StyleDictionary({
  source: ["tokens/01-primitive.json", "tokens/02-semantic.json", "tokens/04-motion.json"],
  preprocessors: ["tokens-studio"],
  platforms: {
    tailwind: {
      transformGroup: "duck/css",
      buildPath: "src/styles/generated/",
      files: [
        {
          destination: "tailwind-tokens.cjs",
          format: "duck/tailwind-tokens",
          filter: (token) => {
            const fp = token.filePath ?? "";
            if (fp.includes("02-semantic") || fp.includes("04-motion")) return true;
            if (fp.includes("01-primitive")) return PRIMITIVE_PASS_THROUGH.includes(token.path[0]);
            return false;
          },
        },
      ],
    },
  },
});

// ─── Run all builds ───────────────────────────────────────────────────────────
console.log("\n🎨 Building design tokens...\n");

await sdLight.buildAllPlatforms();
console.log("  ✓ Light-mode CSS  → src/styles/generated/tokens.css");

await sdDark.buildAllPlatforms();
console.log("  ✓ Dark-mode CSS   → src/styles/generated/dark.css");

await sdTS.buildAllPlatforms();
console.log("  ✓ TypeScript obj  → src/lib/generated/tokens.ts");

await sdTailwind.buildAllPlatforms();
console.log("  ✓ Tailwind ext    → src/styles/generated/tailwind-tokens.cjs");

console.log("\n✅ Token build complete!\n");
