/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ds: {
          bg: 'var(--ds-bg)',
          surface: 'var(--ds-surface)',
          'surface-elevated': 'var(--ds-surface-elevated)',
          border: 'var(--ds-border)',
          'text-primary': 'var(--ds-text-primary)',
          'text-secondary': 'var(--ds-text-secondary)',
          'text-muted': 'var(--ds-text-muted)',
          'text-inverse': 'var(--ds-text-inverse)',
          accent: 'var(--ds-accent)',
          'accent-hover': 'var(--ds-accent-hover)',
          destructive: 'var(--ds-destructive)',
          'destructive-pressed': 'var(--ds-destructive-pressed)',
          black: 'var(--ds-black)',
          white: 'var(--ds-white)',
          success: 'var(--ds-success)',
          warning: 'var(--ds-warning)',
          danger: 'var(--ds-danger)',
        },
      },
      fontFamily: {
        sans: ['Roboto', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"SF Mono"', 'monospace'],
      },
      fontSize: {
        'ds-xs': ['10px', { lineHeight: '14px' }],
        'ds-sm': ['14px', { lineHeight: '20px' }],
        'ds-base': ['16px', { lineHeight: '24px' }],
        'ds-lg': ['20px', { lineHeight: '24px' }],
        'ds-xl': ['24px', { lineHeight: '32px' }],
        'ds-2xl': ['32px', { lineHeight: '40px' }],
        'ds-3xl': ['40px', { lineHeight: '48px' }],
      },
      spacing: {
        'ds-1': '4px',
        'ds-2': '8px',
        'ds-3': '12px',
        'ds-4': '16px',
        'ds-5': '20px',
        'ds-6': '24px',
        'ds-8': '32px',
        'ds-10': '40px',
        'ds-12': '48px',
        'ds-16': '64px',
      },
      borderRadius: {
        'ds-none': '0',
        'ds-sm': '4px',
        'ds-md': '8px',
        'ds-lg': '16px',
        'ds-xl': '20px',
        'ds-full': '9999px',
      },
      boxShadow: {
        'ds-sm': '0 0 6px rgba(0,0,0,0.16), 0 2px 4px rgba(0,0,0,0.16)',
        'ds-md': '0 2px 8px rgba(0,0,0,0.12), 0 4px 16px rgba(0,0,0,0.08)',
        'ds-lg': '0 4px 16px rgba(0,0,0,0.16), 0 8px 32px rgba(0,0,0,0.12)',
      },
    },
  },
  plugins: [],
}
