/**
 * Button — shadcn/ui-style component wired to design tokens.
 *
 * Colors come from CSS custom properties generated by Style Dictionary:
 *   --color-interactive-primary        → bg-interactive-primary
 *   --color-interactive-primary-hover  → hover:bg-interactive-primary-hover
 *   --color-interactive-secondary      → bg-interactive-secondary
 *   etc.
 *
 * Dark-mode variants are handled automatically because the .dark class
 * swaps the CSS vars — zero component-level changes needed.
 */

import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const buttonVariants = cva(
  // Base styles
  [
    "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md",
    "text-sm font-medium ring-offset-background",
    "transition-colors duration-token-fast ease-token-ease-out",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
    "disabled:pointer-events-none disabled:opacity-50",
    "[&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  ],
  {
    variants: {
      variant: {
        // Uses design-token CSS vars → auto dark-mode via .dark swap
        default:
          "bg-interactive-primary text-interactive-primary-text hover:bg-interactive-primary-hover active:bg-[var(--color-interactive-primary-active)]",

        secondary:
          "bg-interactive-secondary text-interactive-secondary-text hover:bg-interactive-secondary-hover",

        ghost:
          "text-text-primary hover:bg-[var(--color-interactive-ghost-hover)]",

        link:
          "text-text-link underline-offset-4 hover:underline hover:text-[var(--color-text-link-hover)]",

        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90",

        outline:
          "border border-border-default bg-bg-surface hover:bg-bg-subtle text-text-primary",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm:      "h-9 rounded-sm px-3 text-xs",
        lg:      "h-11 rounded-lg px-8",
        icon:    "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    );
  }
);
Button.displayName = "Button";

export { Button, buttonVariants };
